import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import BottomHeader from "@/components/bottomheader";

export const metadata = {
  title: "Lama Store || Shop your desired products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <BottomHeader />
        {children}
      </body>
    </html>
  );
}
